### ISSUE TITLE
This site cannot be reached

### ISSUE THREAD

**Issue by sumanth2002629** [mskian/cricket-api#11]
I was running php server in the localhost and entered the URL in the browser. But the site cannot be reached.

I am using **php -S localhost:6001**  to run the server and entered the **URL: http://localhost:6001/cri.php?url=https://www.cricbuzz.com/live-cricket-scores/38337/1st-odi-south-africa-tour-of-england-2022**.

But I was getting the following error in the terminal
![cricket_api_seerver](https://user-images.githubusercontent.com/76842817/179795182-6a343b66-e871-4a19-99eb-406a07f278b4.png)

![cricket_api_browser](https://user-images.githubusercontent.com/76842817/179795227-de673c5c-0791-4242-b415-5838b1b34778.png)

**Comment by mskian** [comment]
seems PHP curl module was missing install it and check

**Comment by sumanth2002629** [comment]
Thank you. It's working now.
